# Q.6
### Importing **`Numpy`**

In [33]:
import numpy as np

- seed to get similar results every time

In [34]:
np.random.seed(42)

-  Create a NumPy array containing marks of 10 students in 5 subjects. Perform:

In [35]:
marks = np.random.randint(50, 101, size=(10, 5))
print(marks)

[[ 88  78  64  92  57]
 [ 70  88  68  72  60]
 [ 60  73  85  89  73]
 [ 52  71  51  73  93]
 [ 79  87  51  70  82]
 [ 61  71  93  74  98]
 [ 76  91  77  65  64]
 [ 96 100  93  52  86]
 [100  56  70  58  88]
 [ 67  53  74  63  99]]


1. Calculate subject-wise average.  

In [36]:
subject_averages = np.mean(marks, axis=0)
print(f"Subject-wise Averages: {subject_averages}")

Subject-wise Averages: [74.9 76.8 72.6 70.8 80. ]


2. Calculate student-wise average.  

In [37]:
student_averages = np.mean(marks, axis=1)
print(f"Student-wise Averages:\n{student_averages}")

Student-wise Averages:
[75.8 71.6 76.  68.  73.8 79.4 74.6 85.4 74.4 71.2]


3. Find highest and lowest marks.  

In [38]:
highest_mark = np.max(marks)
lowest_mark = np.min(marks)
print(f"Highest Mark Overall: {highest_mark} | Lowest Mark Overall: {lowest_mark}")

Highest Mark Overall: 100 | Lowest Mark Overall: 51


4. Find students scoring above the overall average.  

In [39]:
overall_average = np.mean(marks)
above_avg_indices = np.where(student_averages > overall_average)[0]
print(f"Overall Average Mark: {overall_average:.2f}")
print(f"Students (0-indexed) scoring above overall average: {above_avg_indices}")

Overall Average Mark: 75.02
Students (0-indexed) scoring above overall average: [0 2 5 7]


5. Find standard deviation for every subject.  

In [40]:
subject_std = np.std(marks, axis=0)
print(f"Subject-wise Standard Deviation: {subject_std}")

Subject-wise Standard Deviation: [15.13571934 14.32340742 14.29125607 11.87265766 14.80540442]


6. Sort students according to their average marks.

In [41]:
sorted_student_indices = np.argsort(student_averages)
print(f"Student indices sorted by performance (lowest to highest average): {sorted_student_indices}")

Student indices sorted by performance (lowest to highest average): [3 9 1 4 8 6 0 2 5 7]


7. Identify the top 3 students.

In [42]:
top_3_students = sorted_student_indices[-3:][::-1]
print(f"Top 3 Student Indices (highest to lowest): {top_3_students}")
print(f"Top 3 Student Averages: {student_averages[top_3_students]}")

Top 3 Student Indices (highest to lowest): [7 5 2]
Top 3 Student Averages: [85.4 79.4 76. ]


# Q. 7
- Create a NumPy array containing salaries of employees.

In [43]:
np.random.seed(101)
salaries = np.random.randint(25000, 120000, size=15)

Mean salary  

In [44]:
mean_salary = np.mean(salaries)
print(f"Mean Salary: ₹{mean_salary:,.2f}")

Mean Salary: ₹77,731.13


Median salary  

In [45]:
median_salary = np.median(salaries)
print(f"Median Salary: ₹{median_salary:,.2f}")

Median Salary: ₹80,293.00


Minimum salary  

In [46]:
max_salary = np.max(salaries)
print(f"Maximum Salary: ₹{max_salary:,.2f}")

Maximum Salary: ₹112,684.00


Minimum salary

In [47]:
min_salary = np.min(salaries)
print(f"Minimum Salary: ₹{min_salary:,.2f}")

Minimum Salary: ₹30,695.00


Standard deviation  

In [48]:
std_salary = np.std(salaries)
print(f"Standard Deviation: ₹{std_salary:,.2f}")

Standard Deviation: ₹26,352.81


Employees earning above average  

In [49]:
above_avg_salaries = salaries[salaries > mean_salary]
print(f"Salaries above average (₹{mean_salary:,.2f}): {above_avg_salaries}")

Salaries above average (₹77,731.13): [108467 108281  98542  80293 102899 112684  86173  96996]


Employees earning between ₹40,000 and ₹80,000  

In [50]:
between_40k_80k = salaries[(salaries >= 40000) & (salaries <= 80000)]
print(f"Employees earning between ₹40,000 and ₹80,000: {between_40k_80k}")

Employees earning between ₹40,000 and ₹80,000: [70919 74751 45463 42357 47056 60391]


Percentage of employees earning above ₹60,000  

In [51]:
above_60k_count = np.sum(salaries > 60000)
total_employees = salaries.size
percentage_above_60k = (above_60k_count / total_employees) * 100
print(f"Percentage earning above ₹60,000: {percentage_above_60k:.2f}% ({above_60k_count}/{total_employees} employees)")

Percentage earning above ₹60,000: 73.33% (11/15 employees)


# Q 9
- Create two NumPy matrices: A = 3 × 3 B = 3 × 3

In [52]:
np.random.seed(24)
A = np.random.randint(1, 10, size=(3, 3))
B = np.random.randint(1, 10, size=(3, 3))

1. Addition  

In [53]:
add_result = A + B
print(f"Matrix Addition (A + B):\n{add_result}\n")


Matrix Addition (A + B):
[[ 7  7  5]
 [12 10  5]
 [10 13  9]]



2. Subtraction  

In [54]:
sub_result = A - B
print(f"Matrix Subtraction (A - B):\n{sub_result}\n")


Matrix Subtraction (A - B):
[[-1  1 -3]
 [ 4 -6 -1]
 [-6 -3  1]]



3. Element-wise multiplication  

In [55]:
elem_mult = A * B
print(f"Element-wise Multiplication (A * B):\n{elem_mult}\n")


Element-wise Multiplication (A * B):
[[12 12  4]
 [32 16  6]
 [16 40 20]]



4. Matrix multiplication  

In [56]:
matrix_mult = A @ B
print(f"Matrix Multiplication (A @ B):\n{matrix_mult}\n")

Matrix Multiplication (A @ B):
[[36 49 28]
 [56 56 46]
 [68 86 43]]



5. Transpose  

In [57]:
transpose_A = A.T
print(f"Transpose of Matrix A (A.T):\n{transpose_A}\n")


Transpose of Matrix A (A.T):
[[3 8 2]
 [4 2 5]
 [1 2 5]]



6. Row-wise sum  

In [58]:
row_sum_A = np.sum(A, axis=1)
print(f"Row-wise Sum of Matrix A: {row_sum_A}\n")

Row-wise Sum of Matrix A: [ 8 12 12]



7. Column-wise sum

In [59]:
col_sum_A = np.sum(A, axis=0)
print(f"Column-wise Sum of Matrix A: {col_sum_A}\n")

Column-wise Sum of Matrix A: [13 11  8]



8. Maximum element  

In [60]:
max_A = np.max(A)
print(f"Maximum Element in Matrix A: {max_A}\n")

Maximum Element in Matrix A: 8



9. Minimum element  

In [61]:
min_A = np.min(A)
print(f"Minimum Element in Matrix A: {min_A}\n")

Minimum Element in Matrix A: 1



10. Calculate determinant  

In [62]:
det_A = np.linalg.det(A)
print(f"Determinant of Matrix A: {det_A:.4f}\n")

Determinant of Matrix A: -108.0000



11. Calculate inverse, if possible  

In [63]:
if det_A != 0:
    inverse_A = np.linalg.inv(A)
    print(f"Inverse of Matrix A (A^-1):\n{inverse_A}\n")

    print("Verification (A @ A^-1 ≈ Identity Matrix):")
    print(np.round(A @ inverse_A))
else:
    print("Inverse of Matrix A is not possible (Matrix is Singular / Det = 0)\n")


11. Inverse of Matrix A (A^-1):
[[ 0.          0.13888889 -0.05555556]
 [ 0.33333333 -0.12037037 -0.01851852]
 [-0.33333333  0.06481481  0.24074074]]

Verification (A @ A^-1 ≈ Identity Matrix):
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]


# Q 11
- Create a NumPy array containing electricity consumption for 12 months.

In [65]:
np.random.seed(42)
monthly_consumption = np.random.randint(150, 450, size=12)
months = np.array(["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"])

for m, c in zip(months, monthly_consumption):
    print(f"{m}: {c} kWh")

Jan: 252 kWh
Feb: 420 kWh
Mar: 256 kWh
Apr: 221 kWh
May: 338 kWh
Jun: 170 kWh
Jul: 252 kWh
Aug: 271 kWh
Sep: 364 kWh
Oct: 237 kWh
Nov: 249 kWh
Dec: 301 kWh


1. Annual consumption

In [68]:
annual_total = np.sum(monthly_consumption)
print(f"Total Annual Consumption: {annual_total} kWh")

Total Annual Consumption: 3331 kWh


2. Monthly average  

In [69]:
monthly_avg = np.mean(monthly_consumption)
print(f"Monthly Average Consumption: {monthly_avg:.2f} kWh")

Monthly Average Consumption: 277.58 kWh


3. Highest consumption month  

In [70]:
max_index = np.argmax(monthly_consumption)
print(f"Highest Consumption Month: {months[max_index]} ({monthly_consumption[max_index]} kWh)")

Highest Consumption Month: Feb (420 kWh)


4. Lowest consumption month  

In [71]:
min_index = np.argmin(monthly_consumption)
print(f"Lowest Consumption Month: {months[min_index]} ({monthly_consumption[min_index]} kWh)")

Lowest Consumption Month: Jun (170 kWh)


5. Months above average  

In [72]:
above_avg_mask = monthly_consumption > monthly_avg
print(f"Months scoring Above Average ({monthly_avg:.2f} kWh):")
print(f"Months: {months[above_avg_mask]}")
print(f"Values: {monthly_consumption[above_avg_mask]}")

Months scoring Above Average (277.58 kWh):
Months: ['Feb' 'May' 'Sep' 'Dec']
Values: [420 338 364 301]


6. Standard deviation  

In [73]:
std_dev = np.std(monthly_consumption)
print(f"Standard Deviation: {std_dev:.2f} kWh")

Standard Deviation: 65.20 kWh


7. Percentage contribution of each month  

In [74]:
percentage_contribution = (monthly_consumption / annual_total) * 100
print("Percentage Contribution of Each Month:")
for m, p in zip(months, percentage_contribution):
    print(f"{m}: {p:.2f}%")

Percentage Contribution of Each Month:
Jan: 7.57%
Feb: 12.61%
Mar: 7.69%
Apr: 6.63%
May: 10.15%
Jun: 5.10%
Jul: 7.57%
Aug: 8.14%
Sep: 10.93%
Oct: 7.11%
Nov: 7.48%
Dec: 9.04%


8. Sort months according to consumption

In [75]:
sorted_indices = np.argsort(monthly_consumption)
print("Months Sorted by Consumption (Lowest to Highest):")
print(f"Months: {months[sorted_indices]}")
print(f"Values: {monthly_consumption[sorted_indices]}")

Months Sorted by Consumption (Lowest to Highest):
Months: ['Jun' 'Apr' 'Oct' 'Nov' 'Jul' 'Jan' 'Mar' 'Aug' 'Dec' 'May' 'Sep' 'Feb']
Values: [170 221 237 249 252 252 256 271 301 338 364 420]


# Q 10
- Create a NumPy matrix representing grayscale pixel values from 0–255.

In [77]:
np.random.seed(42)
image_matrix = np.random.randint(0, 256, size=(6, 6))

print(image_matrix)

[[102 179  92  14 106  71]
 [188  20 102 121 210 214]
 [ 74 202  87 116  99 103]
 [151 130 149  52   1  87]
 [235 157  37 129 191 187]
 [ 20 160 203  57  21 252]]


1. Find minimum and maximum pixel values.  

In [78]:
min_pixel = np.min(image_matrix)
max_pixel = np.max(image_matrix)
print(f"Minimum Pixel Value: {min_pixel} | Maximum Pixel Value: {max_pixel}\n")

Minimum Pixel Value: 1 | Maximum Pixel Value: 252



2. Calculate mean intensity.  

In [79]:
mean_intensity = np.mean(image_matrix)
print(f"Mean Intensity: {mean_intensity:.2f}\n")

Mean Intensity: 119.97



3. Convert the image to binary using a threshold.  

In [80]:
threshold = 127
binary_image = (image_matrix > threshold).astype(int)
print(f"Binary Image (Threshold = {threshold}):\n{binary_image}\n")

Binary Image (Threshold = 127):
[[0 1 0 0 0 0]
 [1 0 0 0 1 1]
 [0 1 0 0 0 0]
 [1 1 1 0 0 0]
 [1 1 0 1 1 1]
 [0 1 1 0 0 1]]



4. Extract a specific region using slicing.  

In [81]:
central_patch = image_matrix[1:4, 1:4]
print(f"Extracted Central Patch (Rows 1-3, Cols 1-3):\n{central_patch}\n")

Extracted Central Patch (Rows 1-3, Cols 1-3):
[[ 20 102 121]
 [202  87 116]
 [130 149  52]]



5. Flip the matrix horizontally and vertically.  

In [82]:
flipped_horizontal = image_matrix[:, ::-1]
flipped_vertical = image_matrix[::-1, :]

print(f"Horizontally Flipped Matrix:\n{flipped_horizontal}\n")
print(f"Vertically Flipped Matrix:\n{flipped_vertical}\n")

Horizontally Flipped Matrix:
[[ 71 106  14  92 179 102]
 [214 210 121 102  20 188]
 [103  99 116  87 202  74]
 [ 87   1  52 149 130 151]
 [187 191 129  37 157 235]
 [252  21  57 203 160  20]]

Vertically Flipped Matrix:
[[ 20 160 203  57  21 252]
 [235 157  37 129 191 187]
 [151 130 149  52   1  87]
 [ 74 202  87 116  99 103]
 [188  20 102 121 210 214]
 [102 179  92  14 106  71]]



6. Calculate row-wise and column-wise intensity.  

In [83]:
row_means = np.mean(image_matrix, axis=1)
col_means = np.mean(image_matrix, axis=0)

print(f"Row-wise Mean Intensities: {np.round(row_means, 2)}")
print(f"Column-wise Mean Intensities: {np.round(col_means, 2)}")

Row-wise Mean Intensities: [ 94.   142.5  113.5   95.   156.   118.83]
Column-wise Mean Intensities: [128.33 141.33 111.67  81.5  104.67 152.33]
